- name: play level variables
  hosts: localhost
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10HRS
    Trainer: SivaKumar
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"
     


